version: '3'

services:
  golang-testcontainers-gherkin-setup-postgres:
    container_name: golang-testcontainers-gherkin-setup-postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
    volumes:
      - ./psql_dump.sql:/docker-entrypoint-initdb.d/1-init.sql
